(define (make-monitored f)
(let ((counter 0))
(lambda (n)
(cond ((and (symbol? n) (eq? n 'how-many-calls?)) counter)
((and (symbol? n) (eq? n 'reset-count))
(begin (set! counter 0)
counter))
(else (begin (set! counter (+ counter 1))
(f n)))))))
