(define rand
  (let ((x random-init))
(lambda (symbol)
(cond ((eq? symbol 'generate)
(begin (set! x (rand-update x))
x))
((eq? symbol 'reset) 
(lambda (y)
(begin (set! x y)
x)))
(else (error "Unknown symbol: RAND" symbol))))))
